n = 4 // number of rows/columns
width = 1 // width of one square
gap = width * 0.5 // gap between squares
spacing = width + gap // amount to shift each square over
height = 10
baseHeight = 1

// total width of the entire shape, across all squares
totalWidth = n * width + (n - 1) * gap

fn square(length, at, offset) {
  return startSketchOn(offsetPlane(XY, offset))
    |> startProfile(at = [
         at[0] - (totalWidth / 2),
         at[1] - (totalWidth / 2)
       ])
    |> xLine(length)
    |> yLine(length)
    |> xLine(length = -length)
    |> yLine(length = -length)
    |> close()
}

fn colorFor(row, column) {
  r = 10 + row * 10
  b = 10 + column * 10
  g = 40
  return appearance::hexString([r, g, b])
}

fn ease(t) {
  return 3 * pow(t, exp = 2) - (2 * pow(t, exp = 3))
}

fn tube(@cellNum) {
  row = rem(cellNum, divisor = n)
  column = floor(cellNum / n)
  at = [row * spacing, column * spacing]

  samples = 10
  fn tubeSample(@i) {
    theta = 90deg / samples * i
    sq = square(length = width, at, offset = height / samples * i)
    return sq
      |> rotate(axis = Z, angle = theta, global = true)
  }
  squares = [0..<samples]
    |> map(f = tubeSample)

  // return loft(squares)
  // |> appearance(color = colorFor(row, column))
  return 1
}

tubes = map([0 ..< n * n], f = tube)
base = square(length = totalWidth, at = [0, 0], offset = -baseHeight)
  |> extrude(length = baseHeight)
