sketch001 = startSketchOn(XY)
profile001 = startProfile(sketch001, at = [-3.95, 1.98])
  |> angledLine(angle = 0deg, length = 7.96, tag = $rectangleSegmentA001)
  |> angledLine(angle = segAng(rectangleSegmentA001) - 90deg, length = 3.97)
  |> angledLine(angle = segAng(rectangleSegmentA001), length = -segLen(rectangleSegmentA001))
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)])
  |> close()
extrude001 = extrude(profile001, length = 4)
shell001 = shell(extrude001, faces = END, thickness = 0.5)


sketch002 = startSketchOn(XY)
profile002 = startProfile(sketch001, at = [-30.95, 10.98])
  |> angledLine(angle = 0deg, length = 7.96, tag = $rectangleSegmentA002)
  |> angledLine(angle = segAng(rectangleSegmentA002) - 90deg, length = 3.97)
  |> angledLine(angle = segAng(rectangleSegmentA002), length = -segLen(rectangleSegmentA002))
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)])
  |> close()
extrude002 = extrude(profile002, length = 4)
shell002= shell(extrude002, faces = END, thickness = 0.5)
