sketch001 = startSketchOn(XY)
profile001 = startProfile(sketch001, at = [-2.35, 1.7])
  |> angledLine(angle = 0deg, length = 5.15, tag = $rectangleSegmentA001)
  |> angledLine(angle = segAng(rectangleSegmentA001) - 90deg, length = 3.92)
  |> angledLine(angle = segAng(rectangleSegmentA001), length = -segLen(rectangleSegmentA001))
  |> line(endAbsolute = [profileStartX(%), profileStartY(%)])
  |> close()
box = extrude(profile001, length = 5)

sketch002 = startSketchOn(XY)
profile002 = circle(sketch002, center = [-2.2, 1.6], radius = 1.09)
cyl1 = extrude(profile002, length = 12, symmetric = true)

sketch003 = startSketchOn(XY)
profile003 = circle(sketch003, center = [-2.76, -2.18], radius = 1.1)
cyl2 = extrude(profile003, length = 5.5, bidirectionalLength = 1)


// final = subtract([box], tools = [cyl1, cyl2])